#!/usr/bin/env ruby

require_relative 'lib/golfmoji'

module Golfmoji
  p 'result:'
  p Executor.new(['⛳', '💥', '©', '🎗'], ARGV).execute

  p 'result:'
  p Executor.new(['⛳', '💥', "'", '📦', '🙊', '🔗'], ARGV).execute

  p 'result:'
  p Executor.new(['⛳', ' ', '✂', '-', '🔗'], ARGV).execute

  p 'result:'
  p Executor.new(['⛳', ' ', '✂', '⛳', '✏'], ARGV).execute

  # https://codegolf.stackexchange.com/questions/126410/sugar-free-syntax
  p 'result:'
  p Executor.new(['💥', "'", '📦', '[]', '🖇', ':', '🔗'], ['abc']).execute

  # https://codegolf.stackexchange.com/questions/126373/am-i-a-fibonacci-number
  p 'result:'
  p Executor.new(['🔎'], ['4']).execute

  # https://codegolf.stackexchange.com/questions/126159/group-a-list-by-frequency
  p 'result:'
  p Executor.new(['📃', '🚬'], ['[1,1,1,4,5,6,6,6,7,7,8,8,8,8,8,8,8,9,5,6,5,6,5,6,5,6,-56]']).execute
end
